// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using DistributedTransactions.Data;

#nullable disable

namespace DistributedTransactions.Data.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("20241122180521_ReferenceData")]
    partial class ReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributedTransactions.Domain.Reference.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("system");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IPOYear")
                        .HasColumnType("integer");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<double?>("MarketCap")
                        .HasColumnType("double precision");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("system");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetClass", "Symbol")
                        .IsUnique();

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            AssetClass = "Cash",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 1776,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "US Dollar",
                            Symbol = "USD"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 2012,
                            Industry = "Biotechnology: Pharmaceutical Preparations",
                            MarketCap = 299760012990.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AbbVie Inc. Common Stock",
                            Sector = "Health Care",
                            Symbol = "ABBV"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AssetClass = "Equity",
                            Country = "Ireland",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 2001,
                            Industry = "Business Services",
                            MarketCap = 226352912962.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accenture plc Class A Ordinary Shares (Ireland)",
                            Sector = "Consumer Discretionary",
                            Symbol = "ACN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Finance: Consumer Services",
                            MarketCap = 203091461787.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "American Express Company Common Stock",
                            Sector = "Finance",
                            Symbol = "AXP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AssetClass = "Equity",
                            Country = "China",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 2014,
                            Industry = "Business Services",
                            MarketCap = 220439190005.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alibaba Group Holding Limited American Depositary Shares each representing eight Ordinary share",
                            Sector = "Consumer Discretionary",
                            Symbol = "BABA"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Major Banks",
                            MarketCap = 352185173594.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bank of America Corporation Common Stock",
                            Sector = "Finance",
                            Symbol = "BAC"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "",
                            MarketCap = 1030494147895.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Berkshire Hathaway Inc.",
                            Sector = "",
                            Symbol = "BRKA"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "",
                            MarketCap = 1031891828217.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Berkshire Hathaway Inc.",
                            Sector = "",
                            Symbol = "BRKB"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Cable & Other Pay Television Services",
                            MarketCap = 233036286183.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Comcast Holdings ZONES",
                            Sector = "Telecommunications",
                            Symbol = "CCZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 2004,
                            Industry = "Computer Software: Prepackaged Software",
                            MarketCap = 317057400000.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Salesforce Inc. Common Stock",
                            Sector = "Technology",
                            Symbol = "CRM"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Integrated oil Companies",
                            MarketCap = 290769376385.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chevron Corporation Common Stock",
                            Sector = "Energy",
                            Symbol = "CVX"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "RETAIL: Building Materials",
                            MarketCap = 402998988916.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home Depot Inc. (The) Common Stock",
                            Sector = "Consumer Discretionary",
                            Symbol = "HD"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Biotechnology: Pharmaceutical Preparations",
                            MarketCap = 365645700758.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Johnson & Johnson Common Stock",
                            Sector = "Health Care",
                            Symbol = "JNJ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Major Banks",
                            MarketCap = 680946387869.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "JP Morgan Chase & Co. Common Stock",
                            Sector = "Finance",
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Beverages (Production/Distribution)",
                            MarketCap = 269452710982.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coca-Cola Company (The) Common Stock",
                            Sector = "Consumer Staples",
                            Symbol = "KO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Biotechnology: Pharmaceutical Preparations",
                            MarketCap = 746380478094.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eli Lilly and Company Common Stock",
                            Sector = "Health Care",
                            Symbol = "LLY"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 2006,
                            Industry = "Business Services",
                            MarketCap = 477639266971.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mastercard Incorporated Common Stock",
                            Sector = "Consumer Discretionary",
                            Symbol = "MA"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Restaurants",
                            MarketCap = 213953973452.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "McDonald's Corporation Common Stock",
                            Sector = "Consumer Discretionary",
                            Symbol = "MCD"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Biotechnology: Pharmaceutical Preparations",
                            MarketCap = 248814962042.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Merck & Company Inc. Common Stock (new)",
                            Sector = "Health Care",
                            Symbol = "MRK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Investment Bankers/Brokers/Service",
                            MarketCap = 213349441727.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Morgan Stanley Common Stock",
                            Sector = "Finance",
                            Symbol = "MS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 2012,
                            Industry = "Computer Software: Prepackaged Software",
                            MarketCap = 214198800000.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ServiceNow Inc. Common Stock",
                            Sector = "Technology",
                            Symbol = "NOW"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            AssetClass = "Equity",
                            Country = "Denmark",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Biotechnology: Pharmaceutical Preparations",
                            MarketCap = 469961989139.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Novo Nordisk A/S Common Stock",
                            Sector = "Health Care",
                            Symbol = "NVO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            AssetClass = "Equity",
                            Country = "Switzerland",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Biotechnology: Pharmaceutical Preparations",
                            MarketCap = 211353114152.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Novartis AG Common Stock",
                            Sector = "Health Care",
                            Symbol = "NVS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 1986,
                            Industry = "Computer Software: Prepackaged Software",
                            MarketCap = 518309564400.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oracle Corporation Common Stock",
                            Sector = "Technology",
                            Symbol = "ORCL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Package Goods/Cosmetics",
                            MarketCap = 393480372081.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Procter & Gamble Company (The) Common Stock",
                            Sector = "Consumer Discretionary",
                            Symbol = "PG"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            AssetClass = "Equity",
                            Country = "Germany",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Computer Software: Prepackaged Software",
                            MarketCap = 270096803558.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SAP  SE ADS",
                            Sector = "Technology",
                            Symbol = "SAP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            AssetClass = "Equity",
                            Country = "Netherlands",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 2022,
                            Industry = "Oil & Gas Production",
                            MarketCap = 204747652705.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shell PLC American Depositary Shares (each representing two (2) Ordinary Shares)",
                            Sector = "Energy",
                            Symbol = "SHEL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            AssetClass = "Equity",
                            Country = "Japan",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Commercial Banks",
                            MarketCap = 280448751621.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sumitomo Mitsui Financial Group Inc Unsponsored American Depositary Shares (Japan)",
                            Sector = "Finance",
                            Symbol = "SMFG"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            AssetClass = "Equity",
                            Country = "Japan",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Auto Manufacturing",
                            MarketCap = 233749936376.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota Motor Corporation Common Stock",
                            Sector = "Consumer Discretionary",
                            Symbol = "TM"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Industrial Machinery/Components",
                            MarketCap = 203880291250.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thermo Fisher Scientific Inc Common Stock",
                            Sector = "Industrials",
                            Symbol = "TMO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            AssetClass = "Equity",
                            Country = "Taiwan",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IPOYear = 1997,
                            Industry = "Semiconductors",
                            MarketCap = 977639076323.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Taiwan Semiconductor Manufacturing Company Ltd.",
                            Sector = "Technology",
                            Symbol = "TSM"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Medical Specialities",
                            MarketCap = 545866652712.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UnitedHealth Group Incorporated Common Stock (DE)",
                            Sector = "Health Care",
                            Symbol = "UNH"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Business Services",
                            MarketCap = 561725893240.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Visa Inc.",
                            Sector = "Consumer Discretionary",
                            Symbol = "V"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Major Banks",
                            MarketCap = 242386919975.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wells Fargo & Company Common Stock",
                            Sector = "Finance",
                            Symbol = "WFC"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Department/Specialty Retail Stores",
                            MarketCap = 678991076668.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Walmart Inc. Common Stock",
                            Sector = "Consumer Discretionary",
                            Symbol = "WMT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            AssetClass = "Equity",
                            Country = "United States",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Integrated oil Companies",
                            MarketCap = 529872597260.0,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Exxon Mobil Corporation Common Stock",
                            Sector = "Energy",
                            Symbol = "XOM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
